name: 'Spigot publish action'
description: 'Publishes a Spigot plugin to SpigotMC'
inputs:
  UPDATE_PAGE:
    description: 'The full spigot update page url'
    required: true
  EMAIL:
    description: 'The email used to login to spigot'
    required: true
  PASSWORD:
    description: 'The password used to login to spigot'
    required: true
  OTP_SECRET:
    description: 'The TOTP secret used to login to spigot'
    required: true
  DOWNLOAD_URL:
    description: 'Download url for the plugin'
    required: true
  IS_FILE:
    description: 'Whether the download url is a file or not'
    required: true
  FILE_NAME:
    description: 'The file name of the uploaded file'
    required: false
  VERSION:
    description: 'The version set for the plugin update'
    required: true
  TITLE:
    description: 'The title set for the plugin update'
    required: true
  DESCRIPTION:
    description: 'The description set for the plugin update'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'