name: 'Spigot publish action'
description: 'Publishes a Spigot plugin to SpigotMC'
inputs:
  UPDATE_PAGE:
    description: 'The full spigot update page url'
    required: true
  EMAIL:
    description: 'The email used to login to spigot'
    required: true
  PASSWORD:
    description: 'The password used to login to spigot'
    required: true
  OTP_SECRET:
    description: 'The TOTP secret used to login to spigot'
    required: true
  EXTERNAL_DOWNLOAD_URL:
    description: 'The link that should be set as the external download url'
    required: false
  FILE_PATH:
    description: 'The path to the file that should be uploaded as the plugin file'
    required: false
  VERSION:
    description: 'The version set for the plugin update'
    required: true
  TITLE:
    description: 'The title set for the plugin update'
    required: true
  DESCRIPTION:
    description: 'The description set for the plugin update'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'